server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/creditdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: notification
    default-schema: notification
    table: flyway_schema_history_notification
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: manual
    properties:
      spring.json.add.type.headers: false
      spring.json.trusted.packages: com.example.notificationservice.dto
      spring.json.value.default.type: com.example.notificationservice.dto.ApplicationDecisionEvent

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5p service=${spring.application.name} requestId=%X{requestId:-} thread=%t logger=%logger{36} msg=\"%m\"%n"
  level:
    org.springframework.kafka: info

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info:
  app:
    name: ${spring.application.name}
