server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditdb
    username: credit
    password: credit
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

credit:
  application:
    outbox:
      publisher:
        polling-interval-ms: 5000
    repair:
      threshold: 2m
      polling-interval-ms: 30000
      check-stuck-applications: true

logging:
  level:
    org.springframework.kafka: info
